name: Auto-close stale issues and PRs
on:
  schedule:
    - cron: '0 0 1,15 * *'  # Runs on the 1st and 15th of each month
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues and PRs
        uses: actions/stale@v9.1.0
        with:
          days-before-stale: 60
          days-before-close: 0
          close-issue-message: 'Closing this issue due to 60 days of inactivity.'
          close-pr-message: 'Closing this PR due to 60 days of inactivity.'
